### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by whippingdot**
do we need licenses in life...

### CODE REVIEW

**Comment by StringentDev** [comment]
@whippingdot use GNU AGPL (GNU Affero General Public License)

**Comment by whippingdot** [comment]
Done

**Comment by StringentDev** [comment]
All done now @whippingdot the GNU AGPL license prevents anyone from changing it legally as well as giving us a lot more control.

**Review by StringentDev — COMMENTED** [review]
All ready, has been submitted now.

**Comment by whippingdot** [comment]
Thanks!

**Pull request merged**
